# steps:
#   - label: ":docker: configure image tag"
#     key: tag:create
#   - commands:
#   - TAG=$(echo "newtag")
#       - buildkite-agent meta-data set "TAG" "$$TAG"
#       - buildkite-agent step update "label" ":sunglasses: TAG=$$TAG"
#     agents:
      # queue: ${BUILD_AGENT}
  #   - label: ":docker: configure image tag"
  # key: "tag:create"
  # command: |
  #   set -euo pipefail

  #   TAG="$(some commands)"
  #   buildkite-agent meta-data set "TAG" "$TAG"

  #   buildkite-agent step update "tag:create"  "label: \":sunglasses: TAG=${TAG}\""
  # agents:
  #   queue: "${BUILD_AGENT}"


# steps:
#   - label: ":mag: Test Annotation"
#     command: |
#       echo "DEPRECATION WARNING: this is a test deprecation message" 2>&1 | tee build.log

#       DEPRECATIONS=$(grep -i "deprecat" build.log | sort -u)

#       if [ -n "$DEPRECATIONS" ]; then
#         echo "$DEPRECATIONS" | buildkite-agent annotate \
#           --style "warning" \
#           --context "deprecations" \
#           --append
#       else
#         buildkite-agent annotate "No deprecation warnings found :white_check_mark:" \
#           --style "success" \
#           --context "deprecations"
#       fi
#     agents:
#       queue: "testqueue"

# steps:
#   - label: "Lint the code"
#     command: "echo 'Linting code...' && false"
#     key: "lint-code"
#   - label: "Block the build if linting fails"
#     depends_on: "lint-code"
#     command: |
#       if [ $$(buildkite-agent step get "outcome" --step "lint-code") != "passed" ]; then
#          cat <<- YAML | buildkite-agent pipeline upload
#          steps:
#            - block: "Blocking build due to lint failure"
#       YAML
#       fi
#     allow_dependency_failure: true
#   - label: "Run tests"
#     command: "echo 'Testing!'"

steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    env:
      MY_VAR: "test_env_var"
      ANOTHER_VAR: "test_env_another"