steps:
  - label: "Test"
    command: "echo hello"

# steps:
#   - label: "My Test"
#     if: build.env("TEST_VAR_CUSTOM") == null
#     command:
#       - "python3 ./src/run.py"
#     agents:
#       - "fixture=${MY_FIXTURE}"
#       - "queue=question"
#     artifact_paths:
#       - "_files/*"

# steps:
#   - label: "My Test"
#     command: "echo Testing agent selection with MY_FIXTURE=${MY_FIXTURE}"
#     agents:
#       - "fixture=${MY_FIXTURE}"
#       - "queue=testqueue"