steps:
  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test

  - label: ":rocket: Deploy event trigger"
    branches: main
    trigger: Pipeline_2
    depends_on: test