steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":arrow_right: Triggering"
    command: echo "pipeline triggered"
    branches: main
    trigger: triggered
    depends_on: build