# steps:
#   - label: ":construction_worker: Build"
#     command: echo "Build the rocket"
#     key: build

#   - label: ":white_check_mark: Test"
#     command: echo "Test the rocket"
#     key: test
#     depends_on: build

#   - label: ":rocket: Deploy"
#     command: |
#       echo "Launch the rocket"
#       cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
#     key: deploy
#     depends_on: test

# steps:
#   - label: "Print value of STEPS_COUNT"
#     command: echo $$STEPS_COUNT


steps:
  - label: ":docker: configure image tag"
    key: tag:create
    commands:
      - TAG=$(some commands)
      - buildkite-agent meta-data set "TAG" "\${TAG}"
      - buildkite-agent step update "label" ":sunglasses: TAG=\${TAG}"
    agents:
      queue: ${BUILD_AGENT}
  # - label: "annotate"
  #   command: "true"
  #   plugins:
  #     - bugcrowd/test-summary#v1.8.0:
  #         inputs:
  #           - label: rspec
  #             artifact_path: artifacts/rspec*
  #             type: junit
  #         formatter:
  #           type: details
  #         context: test-summary
