steps:
  - command: "./src/flaky.sh"
    hard fail: true
    retry:
      automatic:
        - exit_status: 1
          limit: 3
# steps:
#   - label: "My Test"
#     if: build.env("TEST_VAR_CUSTOM") == null
#     command:
#       - "python3 ./src/run.py"
#     agents:
#       - "fixture=${MY_FIXTURE}"
#       - "queue=question"
#     artifact_paths:
#       - "_files/*"

# steps:
#   - label: "My Test"
#     command: "echo Testing agent selection with MY_FIXTURE=${MY_FIXTURE}"
#     agents:
#       - "fixture=${MY_FIXTURE}"
#       - "queue=testqueue"